stages:
  - build
##############################################
build-dev:
  stage: build
  script:
    - echo 开始构建Dinky
    - mvn -B clean package -Dmaven.test.skip=true -P prod,scala-2.12,flink-single-version,flink-1.18,aliyun,web,fast
    - echo 构建完成
    - coscli cp build/dinky-release-1.18-1.0.0-rc4.tar.gz cos://flink-checkpoint-1251517753/data/lib/dinky/dinky-release-1.18-1.0.0-rc4.tar.gz
  tags:
    - dinky
  only:
    - development


build-master:
  stage: build
  script:
    - echo 开始构建jar包
    - mvn clean package -pl scps-shaded -am -Dmaven.test.skip=true
    - echo 构建完成
    - coscli cp scps-shaded/target/scps-shaded-1.0-RELEASE.jar cos://flink-checkpoint-1251517753/data/app/master/scps-shaded-1.0-RELEASE.jar
  tags:
    - dinky
  only:
    - master
